<template>
  <div
    v-if="show"
    class="fixed inset-0 bg-black bg-opacity-50 dark:bg-black/50 flex items-center justify-center z-50"
    @click="close"
  >
    <div
      class="bg-zinc-100 dark:bg-zinc-900 rounded-lg shadow-lg w-full max-w-md mx-4"
      @click.stop
    >
      <!-- Header -->
      <div class="flex items-center justify-between p-4 border-b border-zinc-200 dark:border-zinc-800">
        <button
          class="text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-300"
          @click="close"
        >
          <UIcon name="i-heroicons-x-mark-20-solid" class="w-6 h-6" />
        </button>
        <h2 class="text-lg font-semibold text-zinc-900 dark:text-white">
          Change Username
        </h2>
        <div class="w-6 h-6" /> <!-- Spacer -->
      </div>

      <!-- Content -->
      <div class="p-4 space-y-4">
        <!-- Current Username -->
        <div>
          <label class="block text-sm font-medium text-zinc-700 dark:text-zinc-300 mb-2">
            Current Username
          </label>
          <div class="p-3 bg-zinc-50 dark:bg-zinc-800 rounded-md text-zinc-600 dark:text-zinc-400">
            @{{ currentUsername }}
          </div>
        </div>

        <!-- New Username -->
        <div>
          <label class="block text-sm font-medium text-zinc-700 dark:text-zinc-300 mb-2">
            New Username
          </label>
          <input
            v-model="newUsername"
            type="text"
            placeholder="Enter new username"
            maxlength="16"
            class="w-full px-3 py-2 border border-zinc-300 dark:border-zinc-600 rounded-md focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent bg-zinc-50 dark:bg-zinc-800 text-zinc-900 dark:text-white"
            :class="{ 'border-red-500 dark:border-red-500': usernameError }"
            @input="validateUsername"
          />
          <div class="flex justify-between items-center mt-1">
            <div>
              <div v-if="usernameError" class="text-red-500 text-xs">
                {{ usernameError }}
              </div>
              <div v-else-if="usernameValid && !checkingAvailability" class="text-green-500 text-xs">
                ✓ Username is available
              </div>
              <div v-else-if="checkingAvailability" class="text-primary-500 text-xs">
                Checking availability...
              </div>
            </div>
            <div class="text-xs ml-auto" :class="newUsername.length > 14 ? 'text-orange-500' : 'text-zinc-500'">
              {{ newUsername.length }} / 16
            </div>
          </div>
        </div>

        <!-- Username Guidelines -->
        <div class="text-sm text-zinc-500 dark:text-zinc-400">
          <p class="font-medium mb-1">Username Guidelines:</p>
          <ul class="list-disc list-inside space-y-1">
            <li>16 characters or less</li>
            <li>No whitespace allowed</li>
            <li>Cannot contain: / \ : * ? " &lt; &gt; |</li>
            <li>Must be unique across the platform</li>
          </ul>
        </div>

        <!-- Error Message -->
        <div v-if="error" class="text-red-500 text-sm text-center p-3 bg-red-50 dark:bg-red-900/20 rounded-md">
          {{ error }}
        </div>
      </div>

      <!-- Footer -->
      <div class="flex gap-3 p-4 border-t border-zinc-200 dark:border-zinc-800">
        <UButton
          color="neutral"
          variant="soft"
          class="flex-1"
          @click="close"
        >
          Cancel
        </UButton>
        <UButton
          color="primary"
          class="flex-1 bg-primary-500 hover:bg-primary-600 text-white"
          :loading="loading"
          :disabled="!canUpdate"
          @click="updateUsername"
        >
          {{ loading ? 'Updating...' : 'Update Username' }}
        </UButton>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { canisterService } from '@/services/CanisterService'
import { isAutoGeneratedUsername } from '@/utils/usernameGenerator'

const auth = useAuthStore()
const show = ref(false)
const loading = ref(false)
const error = ref('')
const newUsername = ref('')
const usernameError = ref('')
const usernameValid = ref(false)
const checkingAvailability = ref(false)

// Debounce timer for username checking
let debounceTimer: NodeJS.Timeout | null = null

const currentUsername = computed(() => auth.userProfile?.username || '')

const canUpdate = computed(() => {
  return newUsername.value.trim() && 
         !usernameError.value && 
         usernameValid.value && 
         newUsername.value !== currentUsername.value &&
         !loading.value
})

// Username validation
const validateUsername = () => {
  // Clear previous timer
  if (debounceTimer) {
    clearTimeout(debounceTimer)
  }

  const username = newUsername.value.trim()
  
  // Basic validation
  if (!username) {
    usernameError.value = ''
    usernameValid.value = false
    return
  }

  if (username.length > 16) {
    usernameError.value = 'Username must be 16 characters or less'
    usernameValid.value = false
    return
  }

  // Check for whitespace or forbidden special characters: / \ : * ? " < > |
  if (username.includes(' ') || /[\/\\:*?"<>|]/.test(username)) {
    usernameError.value = 'Username cannot contain whitespace or special characters'
    usernameValid.value = false
    return
  }

  if (username === currentUsername.value) {
    usernameError.value = 'This is already your current username'
    usernameValid.value = false
    return
  }

  usernameError.value = ''
  
  // Check availability after debounce
  debounceTimer = setTimeout(async () => {
    checkingAvailability.value = true
    try {
      const isAvailable = await canisterService.isUsernameAvailable(username)
      usernameValid.value = isAvailable
      if (!isAvailable) {
        usernameError.value = 'Username is already taken'
      }
    } catch (err) {
      console.error('Error checking username availability:', err)
      usernameError.value = 'Error checking username availability'
      usernameValid.value = false
    } finally {
      checkingAvailability.value = false
    }
  }, 500)
}

// Public API
const open = () => {
  show.value = true
  newUsername.value = ''
  error.value = ''
  usernameError.value = ''
  usernameValid.value = false
}

const close = () => {
  show.value = false
  newUsername.value = ''
  error.value = ''
  usernameError.value = ''
  usernameValid.value = false
  
  // Clear debounce timer
  if (debounceTimer) {
    clearTimeout(debounceTimer)
  }
}

const updateUsername = async () => {
  if (!canUpdate.value) return

  loading.value = true
  error.value = ''

  try {
    const updatedUser = await canisterService.updateUsername(newUsername.value.trim())
    
    // Update auth store
    auth.userProfile = updatedUser

    // Show success message
    const toast = useToast()
    toast.add({
      title: 'Username Updated',
      description: `Your username has been changed to @${updatedUser.username}`,
      color: 'success',
    })

    close()
  } catch (err: unknown) {
    console.error('Failed to update username:', err)
    error.value = err instanceof Error ? err.message : 'Failed to update username. Please try again.'
  } finally {
    loading.value = false
  }
}

defineExpose({ open, close })
</script>
