<template>
  <div
    v-if="show"
    class="fixed inset-0 bg-black bg-opacity-50 dark:bg-black/50 flex items-center justify-center z-50"
    @click="close"
  >
    <div
      class="bg-zinc-50 dark:bg-neutral-900 rounded-lg shadow-lg w-full max-w-md mx-4"
      @click.stop
    >
      <!-- Header -->
      <div class="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700">
        <button
          class="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
          @click="close"
        >
          <UIcon name="i-heroicons-x-mark-20-solid" class="w-6 h-6" />
        </button>
        <h2 class="text-lg font-semibold text-gray-900 dark:text-white">
          Change Username
        </h2>
        <div class="w-6 h-6" /> <!-- Spacer -->
      </div>

      <!-- Content -->
      <div class="p-4 space-y-4">
        <!-- Current Username -->
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            Current Username
          </label>
          <div class="p-3 bg-gray-100 dark:bg-gray-800 rounded-md text-gray-600 dark:text-gray-400">
            @{{ currentUsername }}
          </div>
        </div>

        <!-- New Username -->
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            New Username
          </label>
          <UInput
            v-model="newUsername"
            placeholder="Enter new username"
            :class="{ 'border-red-500': usernameError }"
            @input="validateUsername"
          />
          <div v-if="usernameError" class="text-red-500 text-sm mt-1">
            {{ usernameError }}
          </div>
          <div v-if="usernameValid && !checkingAvailability" class="text-green-500 text-sm mt-1">
            ✓ Username is available
          </div>
          <div v-if="checkingAvailability" class="text-blue-500 text-sm mt-1">
            Checking availability...
          </div>
        </div>

        <!-- Username Guidelines -->
        <div class="text-sm text-gray-500 dark:text-gray-400">
          <p class="font-medium mb-1">Username Guidelines:</p>
          <ul class="list-disc list-inside space-y-1">
            <li>3-20 characters long</li>
            <li>Letters, numbers, and underscores only</li>
            <li>Must start with a letter</li>
            <li>Must be unique across the platform</li>
          </ul>
        </div>

        <!-- Error Message -->
        <div v-if="error" class="text-red-500 text-sm text-center p-3 bg-red-50 dark:bg-red-900/20 rounded-md">
          {{ error }}
        </div>
      </div>

      <!-- Footer -->
      <div class="flex gap-3 p-4 border-t border-gray-200 dark:border-gray-700">
        <UButton
          color="neutral"
          variant="soft"
          class="flex-1"
          @click="close"
        >
          Cancel
        </UButton>
        <UButton
          color="primary"
          class="flex-1"
          :loading="loading"
          :disabled="!canUpdate"
          @click="updateUsername"
        >
          {{ loading ? 'Updating...' : 'Update Username' }}
        </UButton>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { canisterService } from '@/services/CanisterService'
import { isAutoGeneratedUsername } from '@/utils/usernameGenerator'

const auth = useAuthStore()
const show = ref(false)
const loading = ref(false)
const error = ref('')
const newUsername = ref('')
const usernameError = ref('')
const usernameValid = ref(false)
const checkingAvailability = ref(false)

// Debounce timer for username checking
let debounceTimer: NodeJS.Timeout | null = null

const currentUsername = computed(() => auth.userProfile?.username || '')

const canUpdate = computed(() => {
  return newUsername.value.trim() && 
         !usernameError.value && 
         usernameValid.value && 
         newUsername.value !== currentUsername.value &&
         !loading.value
})

// Username validation
const validateUsername = () => {
  // Clear previous timer
  if (debounceTimer) {
    clearTimeout(debounceTimer)
  }

  const username = newUsername.value.trim()
  
  // Basic validation
  if (!username) {
    usernameError.value = ''
    usernameValid.value = false
    return
  }

  if (username.length < 3 || username.length > 20) {
    usernameError.value = 'Username must be 3-20 characters long'
    usernameValid.value = false
    return
  }

  if (!/^[a-zA-Z][a-zA-Z0-9_]*$/.test(username)) {
    usernameError.value = 'Username must start with a letter and contain only letters, numbers, and underscores'
    usernameValid.value = false
    return
  }

  if (username === currentUsername.value) {
    usernameError.value = 'This is already your current username'
    usernameValid.value = false
    return
  }

  usernameError.value = ''
  
  // Check availability after debounce
  debounceTimer = setTimeout(async () => {
    checkingAvailability.value = true
    try {
      const isAvailable = await canisterService.isUsernameAvailable(username)
      usernameValid.value = isAvailable
      if (!isAvailable) {
        usernameError.value = 'Username is already taken'
      }
    } catch (err) {
      console.error('Error checking username availability:', err)
      usernameError.value = 'Error checking username availability'
      usernameValid.value = false
    } finally {
      checkingAvailability.value = false
    }
  }, 500)
}

// Public API
const open = () => {
  show.value = true
  newUsername.value = ''
  error.value = ''
  usernameError.value = ''
  usernameValid.value = false
}

const close = () => {
  show.value = false
  newUsername.value = ''
  error.value = ''
  usernameError.value = ''
  usernameValid.value = false
  
  // Clear debounce timer
  if (debounceTimer) {
    clearTimeout(debounceTimer)
  }
}

const updateUsername = async () => {
  if (!canUpdate.value) return

  loading.value = true
  error.value = ''

  try {
    const updatedUser = await canisterService.updateUsername(newUsername.value.trim())
    
    // Update auth store
    auth.userProfile = updatedUser

    // Show success message
    const toast = useToast()
    toast.add({
      title: 'Username Updated',
      description: `Your username has been changed to @${updatedUser.username}`,
      color: 'success',
    })

    close()
  } catch (err: unknown) {
    console.error('Failed to update username:', err)
    error.value = err instanceof Error ? err.message : 'Failed to update username. Please try again.'
  } finally {
    loading.value = false
  }
}

defineExpose({ open, close })
</script>
