[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.14"
ic-cdk = "0.17.2"
ic-cdk-macros = "0.17.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
hex = "0.4.3"
getrandom = { version = "*", default-features = false, features = ["custom"] }
rand = { version = "0.8", default-features = false, features = ["std"] }
ic-http-certification = "3.0"
ic-evm-utils = { version = "4.0.0", default-features = false }
primitive-types = "0.12"
ethabi = "18.0"
rlp = "0.5"
ethers-core = "2.0"
sha3 = "0.10"

# Solana Integration - Using remote sol_rpc canister instead of direct dependencies
bs58 = "0.5.1"
bincode = "1.3.3" 
