[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.14"
ic-cdk = "0.17.2"
ic-cdk-macros = "0.17.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
hex = "0.4.3"
getrandom = { version = "*", default-features = false, features = ["custom"] }
rand = { version = "0.8", default-features = false, features = ["std"] }
ic-http-certification = "3.0"
ic-evm-utils = { version = "4.0.0", default-features = false }
primitive-types = "0.12"
ethabi = "18.0"
rlp = "0.5"
ethers-core = "2.0"
sha3 = "0.10"

# Solana Integration - Using official SOL RPC canister
bs58 = "0.5.1"
bincode = "1.3.3"
base64 = "0.21"

# ECDSA for Solana transaction signing
k256 = "0.13"
ecdsa = "0.16"

# SOL RPC canister client - using official libraries
sol_rpc_client = { version = "3.0.0", features = ["ed25519"] }
sol_rpc_types = "3.0.0"
solana-hash = "3.0.0"
solana-instruction = "3.0.0"
solana-message = "3.0.0"
solana-pubkey = { version = "3.0.0", features = ["curve25519"] }
solana-signature = "3.1.0"
solana-system-interface = { version = "2.0.0", features = ["bincode"] }
solana-transaction = { version = "3.0.0", features = ["bincode"] }
spl-associated-token-account-interface = "2.0.0"
ic-ed25519 = "0.2.0"
num = "0.4.3" 
