/**
 * Generate a random username with nomenclature like user9593
 * Similar to Binance's auto-generated usernames
 */

export function generateRandomUsername(): string {
  // Generate a random number between 1000 and 99999
  const randomNumber = Math.floor(Math.random() * 98999) + 1000
  
  // Return username in format: user + random number
  return `user${randomNumber}`
}

/**
 * Generate multiple random usernames for testing
 */
export function generateMultipleUsernames(count: number): string[] {
  const usernames = new Set<string>()
  
  while (usernames.size < count) {
    usernames.add(generateRandomUsername())
  }
  
  return Array.from(usernames)
}

/**
 * Check if a username follows the auto-generated pattern
 */
export function isAutoGeneratedUsername(username: string): boolean {
  return /^user\d{4,5}$/.test(username)
}
