name: Staging Build

on:
  push:
    branches: [staging]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: '22'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build frontend
      run: npm run build
    - name: Add PTR robots.txt
      run: |
        echo -e "User-agent: *\nDisallow: /" > dist/robots.txt
    - uses: webfactory/ssh-agent@v0.10.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Add Server to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy to PTR via Rsync
      run: |
        rsync -avz --delete dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/zroot/jails/ionicswap/var/www/ptr.ionicswap.com/dist/
